Debug string calc_value IssueID #2484: FULL_DURATION feature profiles
- calc_value in get_calculated_features sometimes generates an error so wrapped
  in try with logging to determine what value is causing:
  ValueError: could not convert string to float

Modified:
skyline/ionosphere/common_functions.py